# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/lookuprequest'
require_relative '../shared/errorresponse'
require_relative '../shared/lookupresponse'

module DingSDK
  module Operations

    class LookupRequest < DingSDK::Utils::FieldAugmented
      extend T::Sig


      field :customer_uuid, String, { 'header': { 'field_name': 'customer-uuid', 'style': 'simple', 'explode': false } }

      field :lookup_request, T.nilable(Shared::LookupRequest), { 'request': { 'media_type': 'application/json' } }


      sig { params(customer_uuid: String, lookup_request: T.nilable(Shared::LookupRequest)).void }
      def initialize(customer_uuid: nil, lookup_request: nil)
        @customer_uuid = customer_uuid
        @lookup_request = lookup_request
      end
    end


    class LookupResponse < DingSDK::Utils::FieldAugmented
      extend T::Sig

      # HTTP response content type for this operation
      field :content_type, String
      # HTTP response status code for this operation
      field :status_code, Integer
      # Bad Request
      field :error_response, T.nilable(Shared::ErrorResponse)
      # OK
      field :lookup_response, T.nilable(Shared::LookupResponse)
      # Raw HTTP response; suitable for custom response parsing
      field :raw_response, T.nilable(Faraday::Response)


      sig { params(content_type: String, status_code: Integer, error_response: T.nilable(Shared::ErrorResponse), lookup_response: T.nilable(Shared::LookupResponse), raw_response: T.nilable(Faraday::Response)).void }
      def initialize(content_type: nil, status_code: nil, error_response: nil, lookup_response: nil, raw_response: nil)
        @content_type = content_type
        @status_code = status_code
        @error_response = error_response
        @lookup_response = lookup_response
        @raw_response = raw_response
      end
    end
  end
end
