# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module DingSDK
  module Models
    module Shared
    
      # AuthenticationStatusResponseDeviceType - The type of device the user is using.
      class AuthenticationStatusResponseDeviceType < T::Enum
        enums do
          ANDROID = new('ANDROID')
          IOS = new('IOS')
          IPADOS = new('IPADOS')
          TVOS = new('TVOS')
          WEB = new('WEB')
        end
      end
    end
  end
end
