# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module DingSDK
  module Shared
  
    # AuthenticationStatusResponseDeviceType - The type of device the user is using.
    class AuthenticationStatusResponseDeviceType < T::Enum
      enums do
        IOS = new('IOS')
        ANDROID = new('ANDROID')
        WEB = new('WEB')
      end
    end
  end
end
