# Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module DingSDK
  module Shared
  
    # Code - A machine-readable code that describes the error.
    class Code < T::Enum
      enums do
        INVALID_PHONE_NUMBER = new('invalid_phone_number')
        INTERNAL_SERVER_ERROR = new('internal_server_error')
        BAD_REQUEST = new('bad_request')
        ACCOUNT_INVALID = new('account_invalid')
        NEGATIVE_BALANCE = new('negative_balance')
        INVALID_LINE = new('invalid_line')
        UNSUPPORTED_REGION = new('unsupported_region')
        INVALID_AUTH_UUID = new('invalid_auth_uuid')
        INVALID_APP_REALM = new('invalid_app_realm')
        UNSUPPORTED_APP_REALM_DEVICE_TYPE = new('unsupported_app_realm_device_type')
        APP_REALM_REQUIRE_DEVICE_TYPE = new('app_realm_require_device_type')
        BLOCKED_NUMBER = new('blocked_number')
        INVALID_APP_VERSION = new('invalid_app_version')
        INVALID_OS_VERSION = new('invalid_os_version')
        INVALID_DEVICE_MODEL = new('invalid_device_model')
        INVALID_DEVICE_ID = new('invalid_device_id')
        NO_ASSOCIATED_AUTH_FOUND = new('no_associated_auth_found')
        DUPLICATED_FEEDBACK_STATUS = new('duplicated_feedback_status')
        INVALID_FEEDBACK_STATUS = new('invalid_feedback_status')
        INVALID_TEMPLATE_ID = new('invalid_template_id')
        SUSPENDED_ACCOUNT = new('suspended_account')
      end
    end

  end
end
