# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module DingSDK
  module Shared
  

    class CreateCheckResponse < ::Crystalline::FieldAugmented
      extend T::Sig

      # The UUID of the corresponding authentication.
      field :authentication_uuid, T.nilable(::String), { 'format_json': { 'letter_case': ::DingSDK::Utils.field_name('authentication_uuid') } }

      field :status, T.nilable(::DingSDK::Shared::CheckStatus), { 'format_json': { 'letter_case': ::DingSDK::Utils.field_name('status'), 'decoder': Utils.enum_from_string(::DingSDK::Shared::CheckStatus, true) } }


      sig { params(authentication_uuid: T.nilable(::String), status: T.nilable(::DingSDK::Shared::CheckStatus)).void }
      def initialize(authentication_uuid: nil, status: nil)
        @authentication_uuid = authentication_uuid
        @status = status
      end
    end
  end
end
