# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module DingSDK
  module Shared
  

    class CreateCheckRequest < ::DingSDK::Utils::FieldAugmented
      extend T::Sig

      # The authentication UUID that was returned when you created the authentication.
      field :authentication_uuid, ::String, { 'format_json': { 'letter_case': ::DingSDK::Utils.field_name('authentication_uuid') } }
      # The code that the user entered.
      field :check_code, ::String, { 'format_json': { 'letter_case': ::DingSDK::Utils.field_name('check_code') } }
      # Your customer UUID, which can be found in the API settings in the Dashboard.
      field :customer_uuid, ::String, { 'format_json': { 'letter_case': ::DingSDK::Utils.field_name('customer_uuid') } }


      sig { params(authentication_uuid: ::String, check_code: ::String, customer_uuid: ::String).void }
      def initialize(authentication_uuid: nil, check_code: nil, customer_uuid: nil)
        @authentication_uuid = authentication_uuid
        @check_code = check_code
        @customer_uuid = customer_uuid
      end
    end
  end
end
