# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module DingSDK
  module Models
    module Shared
    

      class CreateCheckRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The authentication UUID that was returned when you created the authentication.
        field :authentication_uuid, ::String, { 'format_json': { 'letter_case': ::DingSDK::Utils.field_name('authentication_uuid') } }
        # The code that the user entered.
        field :check_code, ::String, { 'format_json': { 'letter_case': ::DingSDK::Utils.field_name('check_code') } }
        # Your customer UUID, which can be found in the API settings in the Dashboard.
        field :customer_uuid, ::String, { 'format_json': { 'letter_case': ::DingSDK::Utils.field_name('customer_uuid') } }


        sig { params(authentication_uuid: ::String, check_code: ::String, customer_uuid: ::String).void }
        def initialize(authentication_uuid: nil, check_code: nil, customer_uuid: nil)
          @authentication_uuid = authentication_uuid
          @check_code = check_code
          @customer_uuid = customer_uuid
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @authentication_uuid == other.authentication_uuid
          return false unless @check_code == other.check_code
          return false unless @customer_uuid == other.customer_uuid
          true
        end
      end
    end
  end
end
