# Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module DingSDK
  module Shared
  
    # DeviceType - The type of device the user is using.
    class DeviceType < T::Enum
      enums do
        IOS = new('IOS')
        ANDROID = new('ANDROID')
        WEB = new('WEB')
      end
    end

  end
end
