# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module DingSDK
  module Shared
  

    class Events < ::Crystalline::FieldAugmented
      extend T::Sig



      
      def initialize; end

      def ==(other)
        return false unless other.is_a? self.class
        true
      end
    end
  end
end
