# Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module DingSDK
  module Shared
  
    # FeedbackRequestStatus - The type of the feedback.
    class FeedbackRequestStatus < T::Enum
      enums do
        ONBOARDED = new('onboarded')
        NOT_ONBOARDED = new('not_onboarded')
      end
    end

  end
end
