# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module DingSDK
  module Models
    module Shared
    

      class FeedbackResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # The UUID of the feedback.
        field :uuid, T.nilable(::String), { 'format_json': { 'letter_case': ::DingSDK::Utils.field_name('uuid') } }


        sig { params(uuid: T.nilable(::String)).void }
        def initialize(uuid: nil)
          @uuid = uuid
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @uuid == other.uuid
          true
        end
      end
    end
  end
end
