# Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module DingSDK
  module Shared
  

    class Security < ::DingSDK::Utils::FieldAugmented
      extend T::Sig


      field :api_key, ::String, { 'security': { 'scheme': true, 'type': 'apiKey', 'sub_type': 'header', 'field_name': 'x-api-key' } }


      sig { params(api_key: ::String).void }
      def initialize(api_key: nil)
        @api_key = api_key
      end
    end
  end
end
