# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module DingSDK
  module Models
    module Errors
    
      # Code - A machine-readable code that describes the error.
      class Code < T::Enum
        enums do
          ACCOUNT_INVALID = new('account_invalid')
          APP_REALM_REQUIRE_DEVICE_TYPE = new('app_realm_require_device_type')
          BAD_REQUEST = new('bad_request')
          BLOCKED_NUMBER = new('blocked_number')
          DUPLICATED_FEEDBACK_STATUS = new('duplicated_feedback_status')
          INTERNAL_SERVER_ERROR = new('internal_server_error')
          INVALID_APP_REALM = new('invalid_app_realm')
          INVALID_APP_VERSION = new('invalid_app_version')
          INVALID_AUTH_UUID = new('invalid_auth_uuid')
          INVALID_DEVICE_ID = new('invalid_device_id')
          INVALID_DEVICE_MODEL = new('invalid_device_model')
          INVALID_FEEDBACK_STATUS = new('invalid_feedback_status')
          INVALID_LINE = new('invalid_line')
          INVALID_OS_VERSION = new('invalid_os_version')
          INVALID_PHONE_NUMBER = new('invalid_phone_number')
          INVALID_SENDER_ID = new('invalid_sender_id')
          INVALID_TEMPLATE_ID = new('invalid_template_id')
          NEGATIVE_BALANCE = new('negative_balance')
          NO_ASSOCIATED_AUTH_FOUND = new('no_associated_auth_found')
          SUSPENDED_ACCOUNT = new('suspended_account')
          UNAUTHORIZED_SENDER_ID = new('unauthorized_sender_id')
          UNSUPPORTED_APP_REALM_DEVICE_TYPE = new('unsupported_app_realm_device_type')
          UNSUPPORTED_REGION = new('unsupported_region')
        end
      end
    end
  end
end
