workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: https://raw.githubusercontent.com/ding-live/openapi/main/ding.yaml
        registry:
            location: registry.speakeasyapi.dev/ding/ding/my-source
targets:
    ding_sdk:
        target: ruby
        source: my-source
        publish:
            rubygems:
                token: $RUBYGEMS_AUTH_TOKEN
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/ding/ding/my-source-code-samples
            blocking: false
