workflowVersion: 1.0.0
sources:
    my-source:
        inputs:
            - location: https://raw.githubusercontent.com/ding-live/openapi/main/ding.yaml
targets:
    ding_sdk:
        target: ruby
        source: my-source
        publish:
            rubygems:
                token: $RUBYGEMS_AUTH_TOKEN
