# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module DingSDK
  module Models
    module Errors
      autoload :APIError, 'ding_sdk/models/errors/apierror.rb'
      autoload :ErrorResponse, 'ding_sdk/models/errors/errorresponse.rb'
      autoload :Code, 'ding_sdk/models/errors/code.rb'
    end
  end
end
