# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module DingSDK
  module Operations
    autoload :CheckResponse, 'ding_sdk/models/operations/check_response.rb'
    autoload :CreateAutenticationResponse, 'ding_sdk/models/operations/create_autentication_response.rb'
    autoload :RetryResponse, 'ding_sdk/models/operations/retry_response.rb'
    autoload :LookupRequest, 'ding_sdk/models/operations/lookup_request.rb'
    autoload :LookupResponse, 'ding_sdk/models/operations/lookup_response.rb'
  end
end
