# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module DingSDK
  module Operations
    autoload :CheckResponse, 'ding_sdk/models/operations/check_response.rb'
    autoload :CreateAuthenticationResponse, 'ding_sdk/models/operations/create_authentication_response.rb'
    autoload :FeedbackResponse, 'ding_sdk/models/operations/feedback_response.rb'
    autoload :GetAuthenticationStatusRequest, 'ding_sdk/models/operations/getauthenticationstatus_request.rb'
    autoload :GetAuthenticationStatusResponse, 'ding_sdk/models/operations/getauthenticationstatus_response.rb'
    autoload :LookupRequest, 'ding_sdk/models/operations/lookup_request.rb'
    autoload :LookupResponse, 'ding_sdk/models/operations/lookup_response.rb'
    autoload :RetryResponse, 'ding_sdk/models/operations/retry_response.rb'
    autoload :Type, 'ding_sdk/models/operations/type.rb'
  end
end
