# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module DingSDK
  module Shared
    autoload :Attempt, 'ding_sdk/models/shared/attempt.rb'
    autoload :AuthenticationStatusResponse, 'ding_sdk/models/shared/authenticationstatusresponse.rb'
    autoload :AuthenticationStatusResponseSchemasEventsType, 'ding_sdk/models/shared/authenticationstatusresponse_schemas_events_type.rb'
    autoload :AuthenticationStatusResponseSchemasStatus, 'ding_sdk/models/shared/authenticationstatusresponse_schemas_status.rb'
    autoload :AuthenticationStatusResponseSchemasType, 'ding_sdk/models/shared/authenticationstatusresponse_schemas_type.rb'
    autoload :AuthenticationStatusResponseDeviceType, 'ding_sdk/models/shared/authenticationstatusresponse_device_type.rb'
    autoload :AuthenticationStatusResponseStatus, 'ding_sdk/models/shared/authenticationstatusresponse_status.rb'
    autoload :AuthenticationStatusResponseType, 'ding_sdk/models/shared/authenticationstatusresponse_type.rb'
    autoload :BalanceUpdate, 'ding_sdk/models/shared/balance_update.rb'
    autoload :Check, 'ding_sdk/models/shared/check.rb'
    autoload :CheckStatus, 'ding_sdk/models/shared/checkstatus.rb'
    autoload :CreateAuthenticationRequest, 'ding_sdk/models/shared/createauthenticationrequest.rb'
    autoload :CreateAuthenticationResponse, 'ding_sdk/models/shared/createauthenticationresponse.rb'
    autoload :CreateCheckRequest, 'ding_sdk/models/shared/createcheckrequest.rb'
    autoload :CreateCheckResponse, 'ding_sdk/models/shared/createcheckresponse.rb'
    autoload :DeliveryStatus, 'ding_sdk/models/shared/delivery_status.rb'
    autoload :ErrorResponse, 'ding_sdk/models/shared/errorresponse.rb'
    autoload :FeedbackRequest, 'ding_sdk/models/shared/feedbackrequest.rb'
    autoload :FeedbackRequestStatus, 'ding_sdk/models/shared/feedbackrequest_status.rb'
    autoload :FeedbackResponse, 'ding_sdk/models/shared/feedbackresponse.rb'
    autoload :LookupResponse, 'ding_sdk/models/shared/lookupresponse.rb'
    autoload :RetryAuthenticationRequest, 'ding_sdk/models/shared/retryauthenticationrequest.rb'
    autoload :RetryAuthenticationResponse, 'ding_sdk/models/shared/retryauthenticationresponse.rb'
    autoload :RetryAuthenticationResponseStatus, 'ding_sdk/models/shared/retryauthenticationresponse_status.rb'
    autoload :Security, 'ding_sdk/models/shared/security.rb'
    autoload :BalanceUpdateType, 'ding_sdk/models/shared/balance_update_type.rb'
    autoload :Capability, 'ding_sdk/models/shared/capability.rb'
    autoload :Code, 'ding_sdk/models/shared/code.rb'
    autoload :DeviceType, 'ding_sdk/models/shared/device_type.rb'
    autoload :Events, 'ding_sdk/models/shared/events.rb'
    autoload :LineType, 'ding_sdk/models/shared/line_type.rb'
    autoload :Signals, 'ding_sdk/models/shared/signals.rb'
    autoload :Status, 'ding_sdk/models/shared/status.rb'
    autoload :Type, 'ding_sdk/models/shared/type.rb'
  end
end
