# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module DingSDK
  module Shared
    autoload :Code, 'ding_sdk/models/shared/code.rb'
    autoload :ErrorResponse, 'ding_sdk/models/shared/errorresponse.rb'
    autoload :CreateCheckResponseStatus, 'ding_sdk/models/shared/createcheckresponse_status.rb'
    autoload :CreateCheckResponse, 'ding_sdk/models/shared/createcheckresponse.rb'
    autoload :CreateCheckRequest, 'ding_sdk/models/shared/createcheckrequest.rb'
    autoload :Status, 'ding_sdk/models/shared/status.rb'
    autoload :CreateAuthenticationResponse, 'ding_sdk/models/shared/createauthenticationresponse.rb'
    autoload :DeviceType, 'ding_sdk/models/shared/device_type.rb'
    autoload :CreateAuthenticationRequest, 'ding_sdk/models/shared/createauthenticationrequest.rb'
    autoload :FeedbackResponse, 'ding_sdk/models/shared/feedbackresponse.rb'
    autoload :FeedbackRequestStatus, 'ding_sdk/models/shared/feedbackrequest_status.rb'
    autoload :FeedbackRequest, 'ding_sdk/models/shared/feedbackrequest.rb'
    autoload :RetryAuthenticationResponseStatus, 'ding_sdk/models/shared/retryauthenticationresponse_status.rb'
    autoload :RetryAuthenticationResponse, 'ding_sdk/models/shared/retryauthenticationresponse.rb'
    autoload :RetryAuthenticationRequest, 'ding_sdk/models/shared/retryauthenticationrequest.rb'
    autoload :LineType, 'ding_sdk/models/shared/line_type.rb'
    autoload :LookupResponse, 'ding_sdk/models/shared/lookupresponse.rb'
    autoload :Security, 'ding_sdk/models/shared/security.rb'
  end
end
