# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module DingSDK
  module Shared
    autoload :Code, 'ding_sdk/models/shared/code.rb'
    autoload :ErrorResponse, 'ding_sdk/models/shared/errorresponse.rb'
    autoload :CreateCheckResponse, 'ding_sdk/models/shared/createcheckresponse.rb'
    autoload :CheckStatus, 'ding_sdk/models/shared/checkstatus.rb'
    autoload :CreateCheckRequest, 'ding_sdk/models/shared/createcheckrequest.rb'
    autoload :Status, 'ding_sdk/models/shared/status.rb'
    autoload :CreateAuthenticationResponse, 'ding_sdk/models/shared/createauthenticationresponse.rb'
    autoload :DeviceType, 'ding_sdk/models/shared/device_type.rb'
    autoload :CreateAuthenticationRequest, 'ding_sdk/models/shared/createauthenticationrequest.rb'
    autoload :FeedbackResponse, 'ding_sdk/models/shared/feedbackresponse.rb'
    autoload :FeedbackRequestStatus, 'ding_sdk/models/shared/feedbackrequest_status.rb'
    autoload :FeedbackRequest, 'ding_sdk/models/shared/feedbackrequest.rb'
    autoload :AuthenticationStatusResponseDeviceType, 'ding_sdk/models/shared/authenticationstatusresponse_device_type.rb'
    autoload :Signals, 'ding_sdk/models/shared/signals.rb'
    autoload :AuthenticationStatusResponse, 'ding_sdk/models/shared/authenticationstatusresponse.rb'
    autoload :RetryAuthenticationResponseStatus, 'ding_sdk/models/shared/retryauthenticationresponse_status.rb'
    autoload :RetryAuthenticationResponse, 'ding_sdk/models/shared/retryauthenticationresponse.rb'
    autoload :RetryAuthenticationRequest, 'ding_sdk/models/shared/retryauthenticationrequest.rb'
    autoload :LineType, 'ding_sdk/models/shared/line_type.rb'
    autoload :LookupResponse, 'ding_sdk/models/shared/lookupresponse.rb'
    autoload :Security, 'ding_sdk/models/shared/security.rb'
  end
end
