# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module DingSDK
  module Operations
  

    class CreateAuthenticationResponse < ::Crystalline::FieldAugmented
      extend T::Sig

      # HTTP response content type for this operation
      field :content_type, ::String
      # Raw HTTP response; suitable for custom response parsing
      field :raw_response, ::Faraday::Response
      # HTTP response status code for this operation
      field :status_code, ::Integer
      # OK
      field :create_authentication_response, T.nilable(::DingSDK::Shared::CreateAuthenticationResponse)
      # Bad Request
      field :error_response, T.nilable(::DingSDK::Shared::ErrorResponse)


      sig { params(content_type: ::String, raw_response: ::Faraday::Response, status_code: ::Integer, create_authentication_response: T.nilable(::DingSDK::Shared::CreateAuthenticationResponse), error_response: T.nilable(::DingSDK::Shared::ErrorResponse)).void }
      def initialize(content_type: nil, raw_response: nil, status_code: nil, create_authentication_response: nil, error_response: nil)
        @content_type = content_type
        @raw_response = raw_response
        @status_code = status_code
        @create_authentication_response = create_authentication_response
        @error_response = error_response
      end

      def ==(other)
        return false unless other.is_a? self.class
        return false unless @content_type == other.content_type
        return false unless @raw_response == other.raw_response
        return false unless @status_code == other.status_code
        return false unless @create_authentication_response == other.create_authentication_response
        return false unless @error_response == other.error_response
        true
      end
    end
  end
end
