# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module DingSDK
  module Operations
  

    class Type < T::Enum
      enums do
        CNAM = new('cnam')
      end
    end
  end
end
